// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_PiTebqqUiu1abbpNEy6_euwQXSyUYwA',
    appId: '1:173030617529:web:97c32ba99297d2cca0c668',
    messagingSenderId: '173030617529',
    projectId: 'mini-chat-bcca5',
    authDomain: 'mini-chat-bcca5.firebaseapp.com',
    storageBucket: 'mini-chat-bcca5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz-WMOnM2yqERsmHJmk8i0edegNat7lVE',
    appId: '1:173030617529:android:ed7b06052f64181da0c668',
    messagingSenderId: '173030617529',
    projectId: 'mini-chat-bcca5',
    storageBucket: 'mini-chat-bcca5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhHu69p-HsZN1IyWvRVIQOpdLVDWUZIDw',
    appId: '1:173030617529:ios:1dc3ef3dc47317cca0c668',
    messagingSenderId: '173030617529',
    projectId: 'mini-chat-bcca5',
    storageBucket: 'mini-chat-bcca5.firebasestorage.app',
    iosBundleId: 'com.example.chatdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhHu69p-HsZN1IyWvRVIQOpdLVDWUZIDw',
    appId: '1:173030617529:ios:1dc3ef3dc47317cca0c668',
    messagingSenderId: '173030617529',
    projectId: 'mini-chat-bcca5',
    storageBucket: 'mini-chat-bcca5.firebasestorage.app',
    iosBundleId: 'com.example.chatdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_PiTebqqUiu1abbpNEy6_euwQXSyUYwA',
    appId: '1:173030617529:web:ff934ff5d654b892a0c668',
    messagingSenderId: '173030617529',
    projectId: 'mini-chat-bcca5',
    authDomain: 'mini-chat-bcca5.firebaseapp.com',
    storageBucket: 'mini-chat-bcca5.firebasestorage.app',
  );
}
